import { DigitalCard } from "./digital-cards-type"		
export const Cards_list:DigitalCard[]= [		
  /* landscape */	{	id: "alms",  frenchName: "Aumône",  artwork: "http://wiki.dominionstrategy.com/images/a/ab/AlmsArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Une fois par tour: si vous n\'avez pas de carte Trésor</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">en jeu, recevez une carte coûtant jusqu\'à      .</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:33px; display: inline;left:370px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "ball",  frenchName: "Bal",  artwork: "http://wiki.dominionstrategy.com/images/thumb/e/e5/BallArt.jpg/452px-BallArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Prenez votre jeton -       .</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">Recevez 2 cartes coûtant chacune jusqu\'à       .</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:12px; display: inline;left:284px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:33px; display: inline;left:370px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "bonfire",  frenchName: "Feu de joie",  artwork: "http://wiki.dominionstrategy.com/images/thumb/4/4c/BonfireArt.jpg/452px-BonfireArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">Écartez jusqu\'à 2 cartes en jeu.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "borrow",  frenchName: "Emprunt",  artwork: "http://wiki.dominionstrategy.com/images/a/af/BorrowArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:10px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Une fois par tour : <div style="display: inline; font-weight: bold;">+1 Achat</div>. Si votre jeton -1 Carte n\'est</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">pas sur votre pioche, placez-le à cet endroit et <div style="display: inline; font-weight: bold;">+</div>       .</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:34px; display: inline;left:380px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "expedition",  frenchName: "Expedition",  artwork: "http://wiki.dominionstrategy.com/images/thumb/c/c0/ExpeditionArt.jpg/452px-ExpeditionArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Piochez 2 cartes supplémentaires</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">pour votre prochaine main.</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "ferry",  frenchName: "Bac",  artwork: "http://wiki.dominionstrategy.com/images/7/7a/FerryArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:18.5px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Placez votre jeton -      sur une pile de cartes Action</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">de la réserve. (Les cartes de cette pile coûtent       de moins</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">à votre tour.)</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:2px; display: inline;left:175px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:24px; display: inline;left:342px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "inheritance",  frenchName: "Héritage",  artwork: "http://wiki.dominionstrategy.com/images/d/dd/InheritanceArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:14px;"><div style="display:inline;"><div style="display:inline; font-size:12px;">Une fois dans la partie : mettez de côté une carte Action non-Ordre de la réserve</div></div><br><div style="display:inline;"><div style="display:inline; font-size:12px;">coûtant jusqu\'à      . Placez dessus votre jeton Domaine. (Durant vos tours, les Domaines </div></div><br><div style="display:inline;"><div style="display:inline; font-size:12px;">sont des Actions qui se lisent « Jouez la carte sous votre jeton Domaine, sans la déplacer ».)</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.12); top:25px; display: inline;left:83px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "lostarts",  frenchName: "Arts anciens",  artwork: "http://wiki.dominionstrategy.com/images/thumb/4/49/LostArtsArt.jpg/452px-LostArtsArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:10px;"><div style="line-height:15px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">Placez votre jeton +1 Action sur une pile de cartes Action de la réserve.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">(Quand vous jouez une carte de cette pile, obtenez d\'abord <div style="display: inline; font-weight: bold;">+1 Action</div>.)</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "mission",  frenchName: "Mission",  artwork: "http://wiki.dominionstrategy.com/images/9/90/MissionArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Une fois par tour : si le tour précédent n\'était pas le vôtre,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">jouez un tour supplémentaire après celui-ci</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">pendant lequel vous ne pourrez pas acheter de carte.</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "pathfinding",  frenchName: "Reconnaissance",  artwork: "http://wiki.dominionstrategy.com/images/a/a3/PathfindingArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:8px;"><div style="line-height:15px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">Placez votre jeton +1 Carte sur une pile de cartes Action de la réserve.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">(Quand vous jouez une carte de cette pile, obtenez d\'abord <div style="display: inline; font-weight: bold;">+1 Carte</div>.)</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "pilgrimage",  frenchName: "Pèlerinage",  artwork: "http://wiki.dominionstrategy.com/images/a/a2/PilgrimageArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:16px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">Une fois par tour : Retournez votre jeton Voyage (placez-le face</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">visible au début de la partie); s\'il est facile visible, choisissez jusqu\'à</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">3 cartes différentes en jeu et recevez un exemplaire de chacune.</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "plan",  frenchName: "Plan de bataille",  artwork: "http://wiki.dominionstrategy.com/images/f/f2/PlanArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Placez votre jeton Écart sur une pile de cartes Action</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">de la réserve. (Quand vous achetez une carte de cette pile,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">vous pouvez écarter une carte de votre main.)</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "quest",  frenchName: "Quête",  artwork: "http://wiki.dominionstrategy.com/images/b/b9/QuestArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Vous pouvez défausser une carte Attaque, deux</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">Malédictions ou six cartes. Dans ce cas, recevez un Or.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "raid",  frenchName: "Raid",  artwork: "http://wiki.dominionstrategy.com/images/2/21/RaidArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Recevez un Argent par Argent que vous avez en jeu. Tous</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">vos adversaires placent leur jeton -1 Carte sur leur pioche.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "save",  frenchName: "Resserre",  artwork: "http://wiki.dominionstrategy.com/images/6/6a/SaveArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">Une fois par tour : <div style="display: inline; font-weight: bold;">+1 Achat</div>. Mettez de côté une carte de votre</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">main et prenez-la en main après la phase Ajustement de ce tour.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "scoutingparty",  frenchName: "Pistage",  artwork: "http://wiki.dominionstrategy.com/images/thumb/0/0d/ScoutingPartyArt.jpg/452px-ScoutingPartyArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+1 Achat</div></div><br></div></div><div style="position:relative; top:-7px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">Consultez les 5 premières cartes de votre pioche.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">Défaussez-en 3 et replacez les autres dans l\'ordre de votre choix.</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "seaway",  frenchName: "Route maritime",  artwork: "http://wiki.dominionstrategy.com/images/e/ec/SeawayArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Recevez une carte Action coûtant jusqu\'à       .</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">Placez votre jeton +1 Achat sur cette pile. (Quand vous jouez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">une carte de cette pile, vous obtenez d\'abord <div style="display: inline; font-weight: bold;">+1 Achat</div>.)</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:1px; display: inline;left:355px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "travellingfair",  frenchName: "Forains",  artwork: "http://wiki.dominionstrategy.com/images/d/d4/Travelling_FairArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+2 Achats</div></div><br></div></div><div style="position:relative; top:-7px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Quand vous recevez une carte à ce tour,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">vous pouvez la placer sur votre pioche.</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "trade",  frenchName: "Commerce",  artwork: "http://wiki.dominionstrategy.com/images/7/72/TraderArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Écartez jusqu\'à 2 cartes de votre main.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">Recevez un Argent par carte écartée.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "training",  frenchName: "Entraînement",  artwork: "http://wiki.dominionstrategy.com/images/3/34/TrainingArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:8px;"><div style="line-height:16px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">Placez votre jeton +      sur une pile de cartes Action de la réserve.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">(Quand vous jouez une carte de cette pile, obtenez d\'abord +      .)</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:10px; display: inline;left:137px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:30px; display: inline;left:397px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "triumph",  frenchName: "Triomphe",  artwork: "http://wiki.dominionstrategy.com/images/9/9d/TriumphArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">Recevez un Domaine. Dans ce cas,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">          par carte que vous avez reçue à ce tour.</div></div><br><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:37px;left:58px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+1</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "annex",  frenchName: "Annexion",  artwork: "http://wiki.dominionstrategy.com/images/4/46/AnnexArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Consultez votre défausse. Mélangez-la toute, sauf</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">au plus 5 cartes, avec votre pioche. Recevez un Duché.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "donate",  frenchName: "Donation",  artwork: "http://wiki.dominionstrategy.com/images/f/f5/DonateArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Après ce tour, prenez en main toutes les cartes de votre pioche</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">et de votre défausse, écartez-en autant que vous le souhaitez,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">mélangez votre main à votre pioche, puis piochez 5 cartes.</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "advance",  frenchName: "Adoubement",  artwork: "http://wiki.dominionstrategy.com/images/3/36/AdvanceArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Vous pouvez écarter une carte Action de votre main.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">Dans ce cas, recevez une carte Action coûtant jusqu\'à      <div class="card-text-coin-icon" style="transform:scale(0.18); top:37px; display: inline;left:401px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">6</div></div></div>.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "delve",  frenchName: "Trouée",  artwork: "http://wiki.dominionstrategy.com/images/b/b5/DelveArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+1 Achat</div></div><br></div><div style="display:inline;"><div style="display:inline; font-size:22px;">Recevez un Argent.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "tax",  frenchName: "Taxe",  artwork: "http://wiki.dominionstrategy.com/images/2/21/TaxArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Ajoutez       <div class="card-text-debt-icon" style="transform:scale(0.18); top:2px; display: inline;left:155px;"><div class="card-text-debt-text-container" style="display:inline;"><div class="card-text-debt-text" style="display:inline; top:48px;">2</div></div></div>à une pile de la réserve.</div></div><br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:4px;"></div><div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Mise en place : ajoutez       <div class="card-text-debt-icon" style="transform:scale(0.18); top:30px; display: inline;left:195px;"><div class="card-text-debt-text-container" style="display:inline;"><div class="card-text-debt-text" style="display:inline; top:48px;">1</div></div></div>à chaque pile de la réserve.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">Quand un joueur achète une carte, il prend les       <div class="card-text-debt-icon" style="transform:scale(0.17); top:51px; display: inline;left:336px;"><div class="card-text-debt-text-container" style="display:inline;"><div class="card-text-debt-text" style="display:inline; top:48px;"></div></div></div>de sa pile.</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "banquet",  frenchName: "Banquet",  artwork: "http://wiki.dominionstrategy.com/images/thumb/2/2b/BanquetArt.jpg/452px-BanquetArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Recevez 2 Cuivres et une carte non-Victoire</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">coûtant jusqu\'à      <div class="card-text-coin-icon" style="transform:scale(0.2); top:35px; display: inline;left:265px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">5</div></div></div>.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "ritual",  frenchName: "Rituel",  artwork: "http://wiki.dominionstrategy.com/images/c/cd/RitualArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Recevez une Malédiction. Dans ce cas, écartez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">une carte de votre main.            par       <div class="card-text-coin-icon" style="transform:scale(0.2); top:36px; display: inline;left:294px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div>de son coût.</div></div><br><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.19); top:37px;left:240px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+1</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "salttheearth",  frenchName: "Ependage de sel",  artwork: "http://wiki.dominionstrategy.com/images/3/32/Salt_the_EarthArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">         </div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">Écartez une carte Victoire de la réserve.</div></div><br><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.19); top:8px;left:220px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+1</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "wedding",  frenchName: "Mariage",  artwork: "http://wiki.dominionstrategy.com/images/2/25/WeddingArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">         </div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">Recevez un Or.</div></div><br><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.19); top:8px;left:220px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+1</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "windfall",  frenchName: "Manne",  artwork: "http://wiki.dominionstrategy.com/images/thumb/f/f0/WindfallArt.jpg/452px-WindfallArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Si votre pioche et votre défausse sont vides, recevez 3 Ors.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "conquest",  frenchName: "Conquête",  artwork: "http://wiki.dominionstrategy.com/images/thumb/9/96/ConquestArt.jpg/452px-ConquestArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">Recevez 2 Argents.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">         par Argent que vous avez reçu à ce tour.</div></div><br><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:38px;left:51px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+1</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "dominate",  frenchName: "Domination",  artwork: "http://wiki.dominionstrategy.com/images/e/e7/DominateArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">Recevez une Province. Dans ce cas,         .</div></div><br><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:7px;left:369px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+9</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "aqueduct",  frenchName: "Aqueduc",  artwork: "http://wiki.dominionstrategy.com/images/0/0b/AqueductArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:16.5px;"><div style="display:inline;"><div style="display:inline; font-size:16.5px;">Lorsque vous recevez un Trésor, déplacez        de sa pile vers ici.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16.5px;">Lorsque vous recevez une carte Victoire, prenez les      d\'ici.</div></div><br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:4px;"></div><div style="position:relative; top:-9px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Mise en place : placez        sur les piles des Argents et des Ors.</div></div><br></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:0px;left:294px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:22px;left:364px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;"></div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.15); top:48px;left:172px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">8</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "arena",  frenchName: "Arène",  artwork: "http://wiki.dominionstrategy.com/images/7/74/ArenaArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:16.5px;"><div style="display:inline;"><div style="display:inline; font-size:16.5px;">Au début de votre phase Achat, vous pouvez défausser</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16.5px;">une carte Action. Dans ce cas, prenez        d\'ici.</div></div><br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:4px;"></div><div style="position:relative; top:-8px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Mise en place : placez ici        par joueur.</div></div><br></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:22px;left:323px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:48px;left:269px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">6</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "banditfort",  frenchName: "Fort des bandits",  artwork: "http://wiki.dominionstrategy.com/images/d/df/Bandit_FortArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Pour le décompte,         <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:8px;left:211px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">-2</div></div><div class="card-text-vp-icon"></div></div>pour chaque Argent</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">et chaque Or que vous avez.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "basilica",  frenchName: "Basilique",  artwork: "http://wiki.dominionstrategy.com/images/6/64/BasilicaArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:16.5px;"><div style="display:inline;"><div style="display:inline; font-size:16.5px;">Lorsque vous achetez une carte, s\'il vous reste       ou plus,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16.5px;">prenez        d\'ici.</div></div><br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:4px;"></div><div style="position:relative; top:-8px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Mise en place : placez ici        par joueur.</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:0px; display: inline;left:332px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:22px;left:223px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:48px;left:269px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">6</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "baths",  frenchName: "Bains",  artwork: "http://wiki.dominionstrategy.com/images/a/a1/BathsArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:16.5px;"><div style="display:inline;"><div style="display:inline; font-size:16.5px;">Si vous terminez votre tour sans avoir reçu une seule carte,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16.5px;">prenez        d\'ici.</div></div><br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:4px;"></div><div style="position:relative; top:-8px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Mise en place : placez ici        par joueur.</div></div><br></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:22px;left:223px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:48px;left:269px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">6</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "battlefield",  frenchName: "Champ de bataille",  artwork: "http://wiki.dominionstrategy.com/images/8/86/BattlefieldArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Lorsque vous recevez une carte Victoire, prenez         <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:6px;left:371px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div>d\'ici.</div></div><br><div class="horizontal-line" style="width:200px; height:3px;margin-top:6px;"></div><div style="position:relative; top:-5px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Mise en place : placez ici         par joueur.</div></div><br></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:40px;left:268px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">6</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "colonnade",  frenchName: "Colonnade",  artwork: "http://wiki.dominionstrategy.com/images/9/94/ColonnadeArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:16.5px;"><div style="display:inline;"><div style="display:inline; font-size:16.5px;">Lorsque vous achetez une carte Action dont vous avez,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16.5px;">un exemplaire en jeu, prenez        d\'ici.</div></div><br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:4px;"></div><div style="position:relative; top:-8px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Mise en place : placez ici        par joueur.</div></div><br></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:21px;left:296px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:48px;left:269px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">6</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "defiledshrine",  frenchName: "Profanation",  artwork: "http://wiki.dominionstrategy.com/images/c/cf/Defiled_ShrineArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:2px;"><div style="position:relative; top:0px;"><div style="line-height:10px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">Quand vous recevez une Action, déplacez        de sa pile vers ici.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">Quand vous achetez une Malédiction, prenez les     d\'ici.</div></div><br></div></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:-2px;"><div style="line-height:10px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">Mise en place : placez         sur chaque pile de carte Action</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;"> non-Collecte de la réserve.</div></div><br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.14); top:0px;left:293px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.14); top:16px;left:350px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;"></div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.14); top:37px;left:188px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "fountain",  frenchName: "Fontaine",  artwork: "http://wiki.dominionstrategy.com/images/5/5b/FountainArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Pour le décompte,           <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:6px;left:162px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">15</div></div><div class="card-text-vp-icon"></div></div>si vous avez au moins 10 Cuivres.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "keep",  frenchName: "Keep",  artwork: "http://wiki.dominionstrategy.com/images/thumb/b/b5/KeepArt.jpg/452px-KeepArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:16.5px;"><div style="display:inline;"><div style="display:inline; font-size:16.5px;">Pour le décompte,          par carte Trésor de nom différent</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16.5px;">dont avez au moins autant d\'exemplaires</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16.5px;">que chacun de vos adversaires.</div></div><br></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.17); top:1px;left:168px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">5</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "labyrinth",  frenchName: "Labyrinthe",  artwork: "http://wiki.dominionstrategy.com/images/8/8d/LabyrinthArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:16.5px;"><div style="display:inline;"><div style="display:inline; font-size:16.5px;">Lorsque vous recevez une deuxième carte à l\'un de vos tours,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16.5px;">prenez        d\'ici.</div></div><br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:4px;"></div><div style="position:relative; top:-8px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Mise en place : placez ici        par joueur.</div></div><br></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:22px;left:224px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:48px;left:269px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">6</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "mountainpass",  frenchName: "Col",  artwork: "http://wiki.dominionstrategy.com/images/4/43/Mountain_PassArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:15px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">Quand vous êtes le premier joueur à recevoir une Province, après ce tour,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">chaque joueur enchérit une fois jusqu\'à       <div class="card-text-debt-icon" style="transform:scale(0.15); top:23px; display: inline;left:264px;"><div class="card-text-debt-text-container" style="display:inline;"><div class="card-text-debt-text" style="display:inline; top:48px;">40</div></div></div> en terminant par vous.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">Le meilleur enchérisseur prend          et les       <div class="card-text-debt-icon" style="transform:scale(0.15); top:41px; display: inline;left:295px;"><div class="card-text-debt-text-container" style="display:inline;"><div class="card-text-debt-text" style="display:inline; top:48px;"></div></div></div>de son enchère.</div></div><br></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.15); top:41px;left:235px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">8</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "museum",  frenchName: "Musée",  artwork: "http://wiki.dominionstrategy.com/images/6/69/MuseumArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Pour le décompte,         <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:7px;left:189px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div>par carte de nom différent</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">que vous avez.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "obelisk",  frenchName: "Obélisque",  artwork: "http://wiki.dominionstrategy.com/images/2/23/ObeliskArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:16.5px;">Pour le décompte,        par carte de la pile choisie que vous avez.</div></div><br><div class="horizontal-line" style="width:200px; height:3px;"></div><div style="position:relative; top:0px;"><div style="line-height:12px;"><div style="display:inline;"><div style="display:inline; font-size:17px;">Mise en place : choisissez au hasard</div></div><br><div style="display:inline;"><div style="display:inline; font-size:17px;">une pile de cartes Action de la réserve.</div></div><br></div></div><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.16); top:9px;left:142px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">2</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "orchard",  frenchName: "Verger",  artwork: "http://wiki.dominionstrategy.com/images/c/c6/OrchardArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Pour le décompte,         <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:8px;left:160px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">4</div></div><div class="card-text-vp-icon"></div></div>par carte Action de nom différent</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">dont vous avez au moins 3 exemplaires.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "palace",  frenchName: "Palais",  artwork: "http://wiki.dominionstrategy.com/images/1/12/PalaceArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Pour le décompte,          <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:8px;left:250px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">3</div></div><div class="card-text-vp-icon"></div></div>par lot de</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Cuivre - Argent - Or que vous avez.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "tomb",  frenchName: "Tombe",  artwork: "http://wiki.dominionstrategy.com/images/5/54/TombArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">Lorsque vous écartez une carte,         <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:7px;left:353px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">+1</div></div><div class="card-text-vp-icon"></div></div>.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "tower",  frenchName: "Tour",  artwork: "http://wiki.dominionstrategy.com/images/2/2f/TowerArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Pour le décompte,        <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:8px;left:200px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">1</div></div><div class="card-text-vp-icon"></div></div>par carte non-Victoire</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">dont la pile de la réserve est vide que vous avez.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "triumphalarch",  frenchName: "Arc de triomphe",  artwork: "http://wiki.dominionstrategy.com/images/c/cb/Triumphal_ArchArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Pour le décompte,          <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:8px;left:170px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">3</div></div><div class="card-text-vp-icon"></div></div>par exemplaire de la deuxième</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">carte Action la plus fréquente parmi vos cartes.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "wall",  frenchName: "Rempart",  artwork: "http://wiki.dominionstrategy.com/images/8/8d/WallArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Pour le décompte,         <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:8px;left:225px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">-1</div></div><div class="card-text-vp-icon"></div></div>par carte, hormis</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">les 15 premières.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "wolfden",  frenchName: "Tanière des loups",  artwork: "http://wiki.dominionstrategy.com/images/0/09/Wolf_DenArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Pour le décompte,         <div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.18); top:8px;left:195px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">-3</div></div><div class="card-text-vp-icon"></div></div>par carte dont vous avez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">exactement un exemplaire.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "theearthsgift",  frenchName: "Don de la terre",  artwork: "http://wiki.dominionstrategy.com/images/3/32/Salt_the_EarthArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Vous pouvez défausser une carte Trésor</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">pour recevoir une carte coûtant jusqu\'à      .</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:33px; display: inline;left:363px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "thefieldsgift",  frenchName: "Don des champs",  artwork: "http://wiki.dominionstrategy.com/images/7/77/The_Field%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="font-weight: bold;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:25px;">+1 Action</div></div><br><div style="display:inline;"><div style="display:inline; font-size:25px;"><div style="position: relative; left:-13px;top:1px;">+</div></div></div><br></div></div><div style="position:relative; top:-32px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">(Conservez ceci jusqu\'à la phase Ajustement.)</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:26px; display: inline;left:218px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "theflamesgift",  frenchName: "Don des flammes",  artwork: "http://wiki.dominionstrategy.com/images/2/22/The_Flame%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:24px;">Vous pouvez écarter une carte de votre main.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "theforestsgift",  frenchName: "Don des forêts",  artwork: "http://wiki.dominionstrategy.com/images/7/73/The_Forest%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="font-weight: bold;"><div style="line-height:25px;"><div style="display:inline;"><div style="display:inline; font-size:25px;">+1 Achat</div></div><br><div style="display:inline;"><div style="display:inline; font-size:25px;"><div style="position: relative; left:-13px;top:1px;">+</div></div></div><br></div></div><div style="position:relative; top:-32px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">(Conservez ceci jusqu\'à la phase Ajustement.)</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:26px; display: inline;left:218px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "themoonsgift",  frenchName: "Don de la lune",  artwork: "http://wiki.dominionstrategy.com/images/c/cd/The_Moon%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">Consultez votre défausse. Vous pouvez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">en placer une carte sur votre pioche.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "themountainsgift",  frenchName: "Don des montagnes",  artwork: "http://wiki.dominionstrategy.com/images/5/53/The_Mountain%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">Recevez un Argent.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "theriversgift",  frenchName: "Don de la rivière",  artwork: "http://wiki.dominionstrategy.com/images/3/33/The_River%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:22px;"><div style="display: inline; font-weight: bold;">+1 Carte</div> à la fin de ce tour.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">(Conservez ceci jusqu\'à la phase Ajustement.)</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "theseasgift",  frenchName: "Don de la mer",  artwork: "http://wiki.dominionstrategy.com/images/8/88/The_Sea%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+1 Carte</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "theskysgift",  frenchName: "Don du ciel",  artwork: "http://wiki.dominionstrategy.com/images/b/bc/The_Sky%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Vous pouvez défausser 3 cartes pour recevoir un Or.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "thesunsgift",  frenchName: "Don du soleil",  artwork: "http://wiki.dominionstrategy.com/images/f/f1/The_Sun%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:0px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Consultez les 4 premières cartes de votre pioche.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;"> Défaussez-en autant que vous le souhaitez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">et replacez le reste dans l\'ordre de votre choix.</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "theswampsgift",  frenchName: "Don des marais",  artwork: "http://wiki.dominionstrategy.com/images/c/c5/The_Swamp%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">Recevez un Feu follet de sa pile.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "thewindsgift",  frenchName: "Don du vent",  artwork: "http://wiki.dominionstrategy.com/images/f/f4/The_Wind%27s_GiftArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+2 Cartes</div></div><br></div><div style="display:inline;"><div style="display:inline; font-size:26px;">Défaussez 2 cartes.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "badomens",  frenchName: "Mauvais augure",  artwork: "http://wiki.dominionstrategy.com/images/1/1b/Bad_OmensArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Placez votre pioche dans votre défausse. Consultez-la</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">et placez en 2 Cuivres sur votre pioche (ou dévoilez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;"> votre défausse pour prouver que c\'est impossible).</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "delusion",  frenchName: "Envoûtemetn",  artwork: "http://wiki.dominionstrategy.com/images/5/58/DelusionArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">Si vous n\'avez pas Envoûté ou Jaloux,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:26px;">prenez Envoûté.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "envy",  frenchName: "Jalousie",  artwork: "http://wiki.dominionstrategy.com/images/b/bd/EnvyArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">Si vous n\'avez pas Envoûté ou Jaloux,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:26px;">prenez Jaloux.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "famine",  frenchName: "Famine",  artwork: "http://wiki.dominionstrategy.com/images/5/51/FamineArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Consultez les 3 premières cartes de votre pioche.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">Défaussez les cartes Action.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">Mélangez le reste dans votre pioche.</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "fear",  frenchName: "Peur",  artwork: "http://wiki.dominionstrategy.com/images/0/09/FearArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Si vous avez au moins 5 cartes en main, défaussez une</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">carte Action ou Trésor (à défaut, dévoilez votre main).</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "greed",  frenchName: "Avidité",  artwork: "http://wiki.dominionstrategy.com/images/f/f8/GreedArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">Recevez un Cuivre sur votre pioche.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "haunting",  frenchName: "Obsession",  artwork: "http://wiki.dominionstrategy.com/images/1/10/HauntingArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">Si vous avez au moins 4 cartes en main,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:26px;">placez-en une sur votre pioche.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "locusts",  frenchName: "Sauterelles",  artwork: "http://wiki.dominionstrategy.com/images/3/38/LocustsArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Écartez la carte du dessus de votre pioche. Si c\'est un</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">Cuivre ou un Domaine, recevez une Malédiction. Sinon,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">recevez une carte moins chère ayant un type en commun.</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "misery",  frenchName: "Détresse",  artwork: "http://wiki.dominionstrategy.com/images/c/ce/MiseryArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Si c\'est votre première Détresse de la partie</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">prenez «En détresse». Sinon, retournez-le</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;"> du côté «En grande détresse».</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "plague",  frenchName: "Peste",  artwork: "http://wiki.dominionstrategy.com/images/1/1d/PlagueArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">Recevez une Malédiction en main.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "poverty",  frenchName: "Pauvreté",  artwork: "http://wiki.dominionstrategy.com/images/e/e2/PovertyArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:26px;">Défaussez jusqu\'à avoir 3 cartes en main.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "war",  frenchName: "Guerre",  artwork: "http://wiki.dominionstrategy.com/images/2/23/WarArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Dévoilez des cartes de votre pioche jusqu\'à en dévoiler</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">une coûtant      ou      . Écartez-la et défaussez le reste.</div></div><br><div class="card-text-coin-icon" style="transform:scale(0.19); top:36px; display: inline;left:107px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">3</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:36px; display: inline;left:157px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "deluded",  frenchName: "Envoûté",  artwork: "http://wiki.dominionstrategy.com/images/5/58/DelusionArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Au début de votre phase Achat, rendez Envoûté, et</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">vous ne pouvez pas acheter de cartes Action à ce tour.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "envious",  frenchName: "Jalous",  artwork: "http://wiki.dominionstrategy.com/images/b/bd/EnvyArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Au début de votre phase Achat, rendez Jaloux, et</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">les cartes Argent et Or produisent       à ce tour.</div></div><br><div class="card-text-coin-icon" style="transform:scale(0.18); top:36px; display: inline;left:306px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "miserable",  frenchName: "En détresse",  artwork: "http://wiki.dominionstrategy.com/images/c/ce/MiseryArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:2px;"><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.55); top:0px;left:200px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">-2</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "twicemiserable",  frenchName: "En grande détresse",  artwork: "http://wiki.dominionstrategy.com/images/c/ce/MiseryArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:2px;"><div class="card-text-vp-icon-container" style="display:inline; transform:scale(0.55); top:0px;left:200px;"><div class="card-text-vp-text-container"><div class="card-text-vp-text" style="top:8px;">-4</div></div><div class="card-text-vp-icon"></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "lostinthewoods",  frenchName: "Perdu dans les bois",  artwork: "http://wiki.dominionstrategy.com/images/f/fb/Lost_in_the_WoodsArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">Au début de votre tour, vous pouvez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:22px;">défausser une carte pour appliquer une Aubaine.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "capitalism",  frenchName: "Capitalisme",  artwork: "http://wiki.dominionstrategy.com/images/1/19/CapitalismArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:10px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">Pendant vos tours, les cartes Action ayant dans leur</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">texte un montant « +      » sont aussi des Trésors.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:35px; display: inline;left:190px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;"></div></div></div></div>'
  /* landscape */	},	
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */		
  /* landscape */	{	id: "flag",  frenchName: "Drapeau",  artwork: "http://wiki.dominionstrategy.com/images/8/82/FlagArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="position:relative; top:5px;"><div style="display:inline;"><div style="display:inline; font-size:24px;">Quand vous piochez votre main, <div style="display: inline; font-weight: bold;">+1 Carte</div>.</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */];		
