import { DigitalCard } from "./digital-cards-type"

export const Cards_list_adventures:DigitalCard[]= [
  
  /* landscape */	{	id: "alms",  frenchName: "Aumône",  artwork: "http://wiki.dominionstrategy.com/images/a/ab/AlmsArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:26px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Une fois par tour: si vous n\'avez pas de carte Trésor</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">en jeu, recevez une carte coûtant jusqu\'à      .</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:33px; display: inline;left:370px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "ball",  frenchName: "Bal",  artwork: "http://wiki.dominionstrategy.com/images/e/e5/BallArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Prenez votre jeton -       .</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">Recevez 2 cartes coûtant chacune jusqu\'à       .</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:12px; display: inline;left:284px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:33px; display: inline;left:370px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "bonfire",  frenchName: "Feu de joie",  artwork: "http://wiki.dominionstrategy.com/images/4/4c/BonfireArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:14px;"><div style="display:inline;"><div style="display:inline; font-size:22px;">Écartez jusqu\'à 2 cartes en jeu.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "borrow",  frenchName: "Emprunt",  artwork: "http://wiki.dominionstrategy.com/images/a/af/BorrowArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:10px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Une fois par tour : <div style="display: inline; font-weight: bold;">+1 Achat</div>. Si votre jeton -1 Carte n\'est</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">pas sur votre pioche, placez-le à cet endroit et <div style="display: inline; font-weight: bold;">+</div>       .</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.2); top:34px; display: inline;left:380px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "expedition",  frenchName: "Expedition",  artwork: "http://wiki.dominionstrategy.com/images/c/c0/ExpeditionArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:10px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Piochez 2 cartes supplémentaires</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">pour votre prochaine main.</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "ferry",  frenchName: "Bac",  artwork: "http://wiki.dominionstrategy.com/images/7/7a/FerryArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:18.5px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Placez votre jeton -      sur une pile de cartes Action</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">de la réserve. (Les cartes de cette pile coûtent       de moins</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">à votre tour.)</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:2px; display: inline;left:175px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.18); top:24px; display: inline;left:342px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "inheritance",  frenchName: "Héritage",  artwork: "http://wiki.dominionstrategy.com/images/d/dd/InheritanceArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:14px;"><div style="display:inline;"><div style="display:inline; font-size:12px;">Une fois dans la partie : mettez de côté une carte Action non-Ordre de la réserve</div></div><br><div style="display:inline;"><div style="display:inline; font-size:12px;">coûtant jusqu\'à      . Placez dessus votre jeton Domaine. (Durant vos tours, les Domaines </div></div><br><div style="display:inline;"><div style="display:inline; font-size:12px;">sont des Actions qui se lisent « Jouez la carte sous votre jeton Domaine, sans la déplacer ».)</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.12); top:25px; display: inline;left:83px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "lostarts",  frenchName: "Arts anciens",  artwork: "http://wiki.dominionstrategy.com/images/4/49/LostArtsArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:10px;"><div style="line-height:15px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">Placez votre jeton +1 Action sur une pile de cartes Action de la réserve.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">(Quand vous jouez une carte de cette pile, obtenez d\'abord <div style="display: inline; font-weight: bold;">+1 Action</div>.)</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "mission",  frenchName: "Mission",  artwork: "http://wiki.dominionstrategy.com/images/9/90/MissionArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Une fois par tour : si le tour précédent n\'était pas le vôtre,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">jouez un tour supplémentaire après celui-ci</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">pendant lequel vous ne pourrez pas acheter de carte.</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "pathfinding",  frenchName: "Reconnaissance",  artwork: "http://wiki.dominionstrategy.com/images/a/a3/PathfindingArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:8px;"><div style="line-height:15px;"><div style="display:inline;"><div style="display:inline; font-size:15px;">Placez votre jeton +1 Carte sur une pile de cartes Action de la réserve.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:15px;">(Quand vous jouez une carte de cette pile, obtenez d\'abord <div style="display: inline; font-weight: bold;">+1 Carte</div>.)</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "pilgrimage",  frenchName: "Pèlerinage",  artwork: "http://wiki.dominionstrategy.com/images/a/a2/PilgrimageArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:16px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">Une fois par tour : Retournez votre jeton Voyage (placez-le face</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">visible au début de la partie); s\'il est facile visible, choisissez jusqu\'à</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">3 cartes différentes en jeu et recevez un exemplaire de chacune.</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "plan",  frenchName: "Plan de bataille",  artwork: "http://wiki.dominionstrategy.com/images/f/f2/PlanArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:18.5px;">Placez votre jeton Écart sur une pile de cartes Action</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">de la réserve. (Quand vous achetez une carte de cette pile,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18.5px;">vous pouvez écarter une carte de votre main.)</div></div><br></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "quest",  frenchName: "Quête",  artwork: "http://wiki.dominionstrategy.com/images/b/b9/QuestArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Vous pouvez défausser une carte Attaque, deux</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">Malédictions ou six cartes. Dans ce cas, recevez un Or.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "raid",  frenchName: "Raid",  artwork: "http://wiki.dominionstrategy.com/images/2/21/RaidArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Recevez un Argent par Argent que vous avez en jeu. Tous</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">vos adversaires placent leur jeton -1 Carte sur leur pioche.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "save",  frenchName: "Resserre",  artwork: "http://wiki.dominionstrategy.com/images/6/6a/SaveArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">Une fois par tour : <div style="display: inline; font-weight: bold;">+1 Achat</div>. Mettez de côté une carte de votre</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">main et prenez-la en main après la phase Ajustement de ce tour.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "scoutingparty",  frenchName: "Pistage",  artwork: "http://wiki.dominionstrategy.com/images/0/0d/ScoutingPartyArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+1 Achat</div></div><br></div></div><div style="position:relative; top:-7px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">Consultez les 5 premières cartes de votre pioche.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">Défaussez-en 3 et replacez les autres dans l\'ordre de votre choix.</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "seaway",  frenchName: "Route maritime",  artwork: "http://wiki.dominionstrategy.com/images/e/ec/SeawayArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Recevez une carte Action coûtant jusqu\'à       .</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">Placez votre jeton +1 Achat sur cette pile. (Quand vous jouez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">une carte de cette pile, vous obtenez d\'abord <div style="display: inline; font-weight: bold;">+1 Achat</div>.)</div></div><br></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:1px; display: inline;left:355px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">4</div></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "travellingfair",  frenchName: "Forains",  artwork: "http://wiki.dominionstrategy.com/images/d/d4/Travelling_FairArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:-5px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:22px;">+2 Achats</div></div><br></div></div><div style="position:relative; top:-7px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Quand vous recevez une carte à ce tour,</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">vous pouvez la placer sur votre pioche.</div></div><br></div></div></div>'
  /* landscape */	},	
  /* landscape */	{	id: "trade",  frenchName: "Commerce",  artwork: "http://wiki.dominionstrategy.com/images/f/f7/TradeArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="display:inline;"><div style="display:inline; font-size:20px;">Écartez jusqu\'à 2 cartes de votre main.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20px;">Recevez un Argent par carte écartée.</div></div><br></div>'
  /* landscape */	},	
  /* landscape */	{	id: "training",  frenchName: "Entraînement",  artwork: "http://wiki.dominionstrategy.com/images/3/34/TrainingArt.jpg",
  /* landscape */		text_html: '<div class="landscape-text" style="top:0px;"><div style="position:relative; top:8px;"><div style="line-height:16px;"><div style="display:inline;"><div style="display:inline; font-size:16px;">Placez votre jeton +      sur une pile de cartes Action de la réserve.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:16px;">(Quand vous jouez une carte de cette pile, obtenez d\'abord +      .)</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:10px; display: inline;left:137px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div><div class="card-text-coin-icon" style="transform:scale(0.16); top:30px; display: inline;left:397px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>'
  /* landscape */	},	
  /* landscape */];		
  