import { DigitalCard } from "./digital-cards-type"

export const Cards_list_Promo:DigitalCard[]= [		
  
/* Promo */  	{	id: "sauna",  frenchName: "Sauna",  artwork: "http://wiki.dominionstrategy.com/images/d/de/SaunaArt.jpg",
    		text_html: '<div class="card-text" style="top:5px;"><div style="font-weight: bold;"><div style="line-height:27px;"><div style="display:inline;"><div style="display:inline; font-size:27px;">+1 Carte</div></div><br><div style="display:inline;"><div style="display:inline; font-size:27px;">+1 Action</div></div><br></div></div><div style="position:relative; top:3px;"><div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Vous pouvez jouer un Trou dans</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">la glace de votre main.</div></div><br></div></div><div class="horizontal-line" style="width:200px; height:2px;margin-top:8px;"></div><div style="position:relative; top:0px;"><div style="line-height:17px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Lorsque cette carte est en jeu, quand</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">vous jouez un Argent, vous pouvez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">écarter une carte de votre main.</div></div><br></div></div></div>'
    	},	
    	{	id: "avanto",  frenchName: "Trou dans la glace",  artwork: "http://wiki.dominionstrategy.com/images/f/f1/AvantoArt.jpg",
    		text_html: '<div class="card-text" style="top:29px;"><div style="position:relative; top:15px;"><div style="font-weight: bold;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:27px;">+3 Cartes</div></div><br></div></div></div><div style="position:relative; top:8px;"><div style="line-height:20px;"><div style="display:inline;"><div style="display:inline; font-size:21px;"></div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">Vous pouvez jouer un Sauna</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">de votre main.</div></div><br></div></div></div>'
    	},	
    	{	id: "blackmarket",  frenchName: "Marché noir",  artwork: "http://wiki.dominionstrategy.com/images/9/93/Black_MarketArt.jpg",
    		text_html: '<div class="card-text" style="top:2px;"><div style="position:relative; top:1px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:26px;">+   </div></div><br></div></div><div style="position:relative; top:-2px;"><div style="line-height:13px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">Dévoilez les 3 premières cartes du paquet</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">du Marché noir. Jouez autant de cartes Trésor</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">de votre main que souhaité. Vous pouvez acheter</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">une des cartes dévoilées. Replacez les autres sous</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">le paquet Marché noir dans l\'ordre de votre choix.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.24); top:2px; display: inline;left:140px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">2</div></div></div><div class="horizontal-line" style="width:200px; height:2px;margin-top:3px;"></div><div style="position:relative; top:-1px;"><div style="line-height:13px;"><div style="display:inline;"><div style="display:inline; font-size:14px;">Mise en place : préparez le paquet du Marché noir</div></div><br><div style="display:inline;"><div style="display:inline; font-size:14px;">avec des cartes Royaume différentes non utilisées.</div></div><br></div></div></div>'
    	},	
    	{	id: "envoy",  frenchName: "Délégué",  artwork: "http://wiki.dominionstrategy.com/images/f/f8/EnvoyArt.jpg",
    		text_html: '<div class="card-text" style="top:29px;"><div style="position:relative; top:15px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Dévoilez les 5 premières cartes de</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">votre pioche. Le joueur à votre</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">gauche en choisit une. Défaussez-la</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">et prenez les autres en main.</div></div><br></div></div></div>'
    	},	
    	{	id: "governor",  frenchName: "Gouverneur",  artwork: "http://wiki.dominionstrategy.com/images/e/e3/GovernorArt.jpg",
    		text_html: '<div class="card-text" style="top:29px;"><div style="position:relative; top:15px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Dévoilez les 5 premières cartes de</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">votre pioche. Le joueur à votre</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">gauche en choisit une. Défaussez-la</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">et prenez les autres en main.</div></div><br></div></div></div>'
    	},	
    	{	id: "prince",  frenchName: "Prince",  artwork: "http://wiki.dominionstrategy.com/images/e/ee/PrincessArt.jpg",
    		text_html: '<div class="card-text" style="top:29px;"><div style="position:relative; top:15px;"><div style="line-height:19px;"><div style="display:inline;"><div style="display:inline; font-size:19px;">Dévoilez les 5 premières cartes de</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">votre pioche. Le joueur à votre</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">gauche en choisit une. Défaussez-la</div></div><br><div style="display:inline;"><div style="display:inline; font-size:19px;">et prenez les autres en main.</div></div><br></div></div></div>'
    	},	
    	{	id: "walledvillage",  frenchName: "Ville fortifiée",  artwork: "http://wiki.dominionstrategy.com/images/e/ea/Walled_VillageArt.jpg",
    		text_html: '<div class="card-text" style="top:10px;"><div style="font-weight: bold;"><div style="display:inline;">+1 Carte</div><br></div><div style="font-weight: bold;"><div style="display:inline;">+2 Actions</div><br></div><div class="horizontal-line" style="width:200px; height:3px;margin-top:5px;"></div><div style="position:relative; top:3px;"><div style="line-height:18px;"><div style="display:inline;"><div style="display:inline; font-size:18px;">Au début de la phase Ajustement, si</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">vous avez cette carte et au plus une</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">autre carte Action en jeu, vous pouvez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:18px;">remettre cette carte sur votre pioche.</div></div><br></div></div></div>'
    	},	
    	{	id: "dismantle",  frenchName: "Démantelement",  artwork: "http://wiki.dominionstrategy.com/images/b/b3/DismantleArt.jpg",
    		text_html: '<div class="card-text" style="top:47px;"><div style="position:relative; top:7px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">Écartez une carte de votre main.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">Si elle coûte      ou plus, recevez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">une carte moins chère et un Or.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:33px; display: inline;left:115px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>'
    	},	
    	{	id: "captain",  frenchName: "Capitaine",  artwork: "http://wiki.dominionstrategy.com",
    		text_html: '<div class="card-text" style="top:47px;"><div style="position:relative; top:7px;"><div style="line-height:21px;"><div style="display:inline;"><div style="display:inline; font-size:21px;">Écartez une carte de votre main.</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">Si elle coûte      ou plus, recevez</div></div><br><div style="display:inline;"><div style="display:inline; font-size:21px;">une carte moins chère et un Or.</div></div><br></div></div><div class="card-text-coin-icon" style="transform:scale(0.19); top:33px; display: inline;left:115px;"><div class="card-text-coin-text-container" style="display:inline;"><div class="card-text-coin-text" style="color: black; display:inline; top:8px;">1</div></div></div></div>'
    	},	
    	{	id: "church",  frenchName: "Eglise",  artwork: "http://wiki.dominionstrategy.com",
    		text_html: '<div class="card-text" style="top:10px;"><div style="font-weight: bold;"><div style="display:inline;"><div style="display:inline; font-size:28px;">+1 Action</div></div><br></div><div style="position:relative; top:10px;"><div style="line-height:22px;"><div style="display:inline;"><div style="display:inline; font-size:20.5px;">Mettez de côté jusqu\'à 3 cartes de</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">votre main, face cachée. Au début</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">de votre prochain tour, prenez-les</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">en main, puis vous pouvez écarter</div></div><br><div style="display:inline;"><div style="display:inline; font-size:20.5px;">une carte de votre main.</div></div><br></div></div></div>'
    	},	

];
